### ISSUE TITLE
Does not work after migrating to Unified API

### ISSUE THREAD

**Issue by gregfiske** [jamesmontemagno/Xamarin.Forms-PullToRefreshListView#2]
ListViewRenderer is now part of Classic API and requires Monotouch to be referenced, which of course won't work with new Unified API which uses Xamain.iOS.

Any suggestions on conversion or upgrade?

**Comment by jamesmontemagno** [comment]
Seems to work fine here. Make sure to remove your nugets and re-add them. I have committed the migrated project.
